HAProxy starts on install and start of cluster

diff --git a/yakko b/yakko
--- a/yakko
+++ b/yakko
@@ -16,12 +16,14 @@
 
 ######## THESE CAN BE USER CONFIGURABLE FOR FURTHER TESTING.
 ######## FEEL FREE TO ADJUST AND TRY YOUR LUCK
-MASTERRAMSIZE=8192 # Recommended 8192. 6000 not enough
-WORKERRAMSIZE=8192 # Recommended ... 2048!? Worked well with 5Gi. Setting up as 8 to do some real work
 MASTERVCPUS=4 # Recommended 4
 WORKERVCPUS=2 # Recommended 2
 MASTERDISKSIZE=20
 WORKERDISKSIZE=20
+
+# THESE CAN BE CHANGED INTERACTIVELY #####################################
+MASTERRAMSIZE=8192 # Recommended 8192. 6000 not enough
+WORKERRAMSIZE=8192 # Recommended ... 2048!? Worked well with 5Gi. Setting up as 8 to do some real work
 CLUSTERNODECONFIG=3 # There are 3 config scenarios, 3+0, 3+1, 3+2 for now
 ##########################################################################
 
@@ -52,7 +54,7 @@ BACKUPDEVICES="/mnt/NFS/YAKKO-BACKUPS /mnt/YAKKO-USB"
 OCPWGETTMP=/tmp/ocpsetupwget.tmp
 OCPVMDISKDIR=/var/lib/libvirt/images
 OCPDOMAIN=localdomain  
-YAKKOOPERATIONALOPTIONS=" startup / shutdown / connect / delete / enable / backup "
+YAKKOOPERATIONALOPTIONS=" startup / shutdown / connect / delete / ops / backup "
 
 
 ################ A FEW REUSABLE FUNCTIONS ################################################
@@ -157,7 +159,7 @@ advance-stage-progression() {
 	else
 		echo _______________________________________________________________________________________
 		echo
-		print-in-green "STAGE ${STAGEPROGRESS}: $1 ($(date +%H:%M))"
+		print-in-green "STAGE ${STAGEPROGRESS}: $1 (Time start: $(date +%H:%M%p))"
 		echo
 	
 		# We write the stage we are at so that we can return if desired
@@ -192,11 +194,21 @@ get-node-list() {
 
 
 check-cluster-state() {
-	# if $1 is 0, don't print state, if $1 is 1 print state
+	# if $1 ==  1 print state
+	# if $1 ==  0 don't print state
 
 	# This is only executed at the end of the process or on subsequent calls
 
 	source ${CLUSTERCONFIGFILE}
+
+	# Are we logged into OpenShift first?
+	oc whoami > /dev/null 2>&1
+	[ $? -eq 1 ] && {
+		echo "You are not authorised in the OpenShift server. Are you logged in?"
+		echo "(try  oc login -u <administrator>)"
+		echo
+		exit
+	}
 
 	# If the web console is available, offer info for it regardless of the output above
 	RESULTCONSOLE=1
@@ -227,7 +239,7 @@ check-cluster-state() {
 	then 
 		# we are asked to print state
 
-		echo CLUSTER: $CLUSTERNAME
+		echo CLUSTER: ${CLUSTERNAME}
 		echo
 
 		if [ $OCPACCESSSTATUS -eq 3 ]
@@ -241,42 +253,42 @@ check-cluster-state() {
 				echo "ERROR: The cluster does not appear to be accessible or there is no console active yet."
 				echo
 
-				echo "You can check the status of the masters by issuing: "
+				echo "You can check the status of the masters by issuing, e.g.: "
 				echo "ssh -i $OCPSSHKEY core@master-0.${CLUSTERNAME}.${OCPDOMAIN}  journalctl -b -f -u crio.service"
 				echo
 				echo or simply: "$0 connect master-0"
 			fi	
 			echo
 			exit
-		else
-			if [ $OCPACCESSSTATUS -eq 0 ] 
-			then
-				echo "The console and API server appear to be operational:"
-			elif [ $OCPACCESSSTATUS -eq 1 ]
-			then
-				echo "The console appears to be operational, the API server does not:"
-			elif [ $OCPACCESSSTATUS -eq 2 ]
-			then
-				echo "The API server appears to be operational, the console does not:"
-			fi
-			echo
-			echo "Web console:  $(${OCPINSTALLSOURCE}/oc whoami --show-console)"
-			echo "API server:   $(${OCPINSTALLSOURCE}/oc whoami --show-server)"
-			echo
-			if [ ! -z "${YAKKOADMIN}" ]
-			then
-				echo "Cluster Administrator: ${YAKKOADMIN}"
-			else
-				echo "Cluster Administrator: kubeadmin"
-				echo "Password:   $(cat ${CLUSTERSETUPDIR}/auth/kubeadmin-password)"
-			fi
-			echo
-			echo "To use the OpenShift 'oc' command from hereon, run \"source ocp-setup-env\" in this shell."
-			echo "You can also call "${YAKKONAME}" with the following parameters: [$YAKKOOPERATIONALOPTIONS"]
+		fi
+
+		if [ $OCPACCESSSTATUS -eq 0 ] 
+		then
+			echo "The console and API server appear to be operational:"
+		elif [ $OCPACCESSSTATUS -eq 1 ]
+		then
+			echo "The console appears to be operational, the API server does not:"
+		elif [ $OCPACCESSSTATUS -eq 2 ]
+		then
+			echo "The API server appears to be operational, the console does not:"
 		fi
 		echo
+		echo "Web console:  $(${OCPINSTALLSOURCE}/oc whoami --show-console)"
+		echo "API server:   $(${OCPINSTALLSOURCE}/oc whoami --show-server)"
+		echo
+		if [ ! -z "${YAKKOADMIN}" ]
+		then
+			echo "Cluster Administrator: ${YAKKOADMIN}"
+		else
+			echo "Cluster Administrator: kubeadmin"
+			echo "Password:   $(cat ${CLUSTERSETUPDIR}/auth/kubeadmin-password)"
+		fi
+		echo
+		echo "To use the OpenShift 'oc' command from hereon, run \"source ocp-setup-env\" in this shell."
+		echo "You can also call "${YAKKONAME}" with the following parameters: [$YAKKOOPERATIONALOPTIONS"]
 	fi
-	
+	echo
+
 	return $OCPACCESSSTATUS
 }
 
@@ -294,24 +306,11 @@ build-ocp-node() {
 	IGNITIONFILE=$6
 
 	echo "Building OCP node: ${NODEHOSTNAME} (MAC Addr: ${NODEMACADDRESS}) - virt install command as follows:"
+	echo
 
 	if [ $(echo ${OCPINSTALLVERSION} | cut -c3 ) -gt 5 ]  # We are on OCP 4.6 or higher
 	then
-		echo
-		echo virt-install \
-			--memory ${NODERAMSIZE} \
-			--vcpus ${NODEVCPUS} \
-			--cpu host \
-			--disk path=${OCPVMDISKDIR}/${NODEHOSTNAME}.${CLUSTERNAME}.${OCPDOMAIN}.qcow2,size=${NODEDISKSIZE},bus=virtio,format=qcow2 \
-			--install kernel=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-live-kernel-x86_64,initrd=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-live-initramfs.x86_64.img,kernel_args_overwrite=yes,kernel_args=\"coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-live-rootfs.x86_64.img coreos.inst.image_url=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-metal.x86_64.raw.gz coreos.inst.ignition_url=${WEBSERVERURL}/${IGNITIONFILE} coreos.inst.insecure ip=dhcp rd.neednet=1\" \
-			--os-type=linux \
-			--os-variant=rhel8-unknown \
-			--graphics vnc \
-			--network network=${NETWORKNAME},mac=${NODEMACADDRESS}  \
-			--noautoconsole --wait -1 \
-			--name ${NODEHOSTNAME}.${CLUSTERNAME}.${OCPDOMAIN}
-
-		virt-install \
+      		virt-install \
 			--memory ${NODERAMSIZE} \
 			--vcpus ${NODEVCPUS} \
 			--cpu host \
@@ -324,19 +323,6 @@ build-ocp-node() {
 			--noautoconsole --wait -1 \
 			--name ${NODEHOSTNAME}.${CLUSTERNAME}.${OCPDOMAIN}
 	else
-		echo
-      		echo virt-install \
-	                --memory ${NODERAMSIZE} \
-	       	         --vcpus ${NODEVCPUS} \
-       		         --cpu host \
-       		         --disk path=${OCPVMDISKDIR}/${NODEHOSTNAME}.${CLUSTERNAME}.${OCPDOMAIN}.qcow2,size=${NODEDISKSIZE},bus=virtio,format=qcow2 \
-       		         --install kernel=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-installer-kernel-x86_64,initrd=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-installer-initramfs.x86_64.img,kernel_args_overwrite=yes,kernel_args=\"coreos.inst=yes coreos.inst.install_dev=vda coreos.inst.image_url=${WEBSERVERURL}/${OCPINSTALLVERSION}/rhcos-metal.x86_64.raw.gz coreos.inst.ignition_url=${WEBSERVERURL}/${IGNITIONFILE} ip=dhcp rd.neednet=1\" \
-       		         --os-type=linux \
-       		         --os-variant=rhel8-unknown \
-       		         --graphics vnc \
-       		         --network network=${NETWORKNAME},mac=${NODEMACADDRESS}  \
-       		         --noautoconsole --wait -1 \
-       		         --name ${NODEHOSTNAME}.${CLUSTERNAME}.${OCPDOMAIN}
 
       		virt-install \
 	                --memory ${NODERAMSIZE} \
@@ -353,25 +339,28 @@ build-ocp-node() {
 	fi
 	echo
 
+	#AQUI ssh-known-host-add
+
 	return $?
 }
 
 
-call-ocp-addons() {
+call-ocp-operations() {
 
 	# This is just nice stuff to have after the install is done
-	# we're here because the user called "yakko enable"
+	# we're here because the user called "yakko ops"
 
 	HTPASSWDFILE=/tmp/ocp-htpasswd
 
 	[ -z "$2" ] && { 
-		echo "USAGE: ${YAKKONAME} enable <OPTION>" 
+		echo "USAGE: ${YAKKONAME} ops <OPTION> [parameters]" 
 		echo
 		echo "Options are:"
-		echo "    - htpasswd admin-username"
-		echo "    - user username"
-		echo "    - localregistry"
-		echo "    - openaccess"
+		echo "    - htpasswd admin-username (deploy local password access and a new administrator)"
+		echo "    - useradd username (add a new user to local password DB)"
+		echo "    - userdelete username (delete an existing user from the local password DB)"
+		echo "    - localregistry (enable a local registry so you can actually use the cluster...)"
+		echo "    - openaccess (enable the cluster to be accessed/used by other machines in your network (via changing HA proxy)"
 		echo
 		exit
 	}
@@ -444,13 +433,13 @@ call-ocp-addons() {
 			echo
 		fi
 
-	elif [ $2 == "user" ]
+	elif [ $2 == "useradd" ]
 	then
 		[ "${YAKKOHTPASSWD}" -eq 1 ] 
 		check-for-error-and-exit $? "You need to first configure Local Passwords via \"YAKKONAME enable htpasswd\"" 
 
 		! [ -z "$3" ] 
-		check-for-error-and-exit $? "Incomplete: you need to also pass a USERNAME for the new account to add" 
+		check-for-error-and-exit $? "Incomplete: you need to also pass a USERNAME for the new user to add" 
 		
 		NEWUSER=$3
 		echo -n "Enter password for user $NEWUSER: "
@@ -478,6 +467,27 @@ call-ocp-addons() {
 		echo "Done - added user $3 and assigned self-provisioner role. You may have to wait a little before you can log in."
 		echo
 
+	elif [ "$2" == "userdelete" ]
+	then
+		[ "${YAKKOHTPASSWD}" -eq 1 ]
+                check-for-error-and-exit $? "You need to first configure Local Passwords via \"YAKKONAME enable htpasswd\""
+
+                ! [ -z "$3" ]
+                check-for-error-and-exit $? "Incomplete: you need to also pass a USERNAME for the username to delete"
+
+		DELUSER=$3
+		oc get secret htpass-secret -n openshift-config -o jsonpath={.data.htpasswd} | base64 -d > ${HTPASSWDFILE}
+
+		cat ${HTPASSWDFILE} | grep $DELUSER
+		if [ $? -eq 0 ]
+		then
+			htpasswd -D ${HTPASSWDFILE} $DELUSER
+			oc patch secret htpass-secret -n openshift-config -p "{\"data\":{\"htpasswd\":\"$(base64 -w0 ${HTPASSWDFILE})\"}}"
+			check-for-error-and-exit $? "Could not update password file in OCP, user not deleted"
+		else
+			echo "User [$DELUSER] not found in OCP, could not delete."	
+		fi
+		
 	elif [ "$2" == "localregistry" ]
 	then
 		query-user "Enabling local registry (images will be lost on registry restart)" "Y" noauto && {
@@ -505,12 +515,14 @@ call-ocp-addons() {
 			done
 			echo Restarting HAPROXY...
 			systemctl restart haproxy
+                        check-for-error-and-exit $? "Could not start HA Proxy, the cluster cannot function without this."
+
 			echo
-			echo "NOTE: You will need to add \"apps.${CLUSTERNAME}.${OCPDOMAIN}\" to your DNS pointing to [hostname]"
+			echo "NOTE: You will need to add \"apps.${CLUSTERNAME}.${OCPDOMAIN}\" to your DNS pointing to [${HOSTNAME}]"
 			echo
 		fi
 	else
-		echo "[$2] is a not a valid command for \"YAKKONAME enable\""
+		echo "[$2] is a not a valid command for \"$YAKKONAME ops\""
 		echo
 	fi
 }
@@ -934,7 +946,7 @@ process-stage-loadbalancer() {
 			} > /etc/haproxy/haproxy.cfg
 
 			setsebool -P haproxy_connect_any 1
-			systemctl restart haproxy
+			systemctl --now enable haproxy
 			check-for-error-and-exit $? "Could not restart haproxy/loadbalancer"
 			systemctl status haproxy --no-pager
 		
@@ -1066,7 +1078,7 @@ process-stage-httpserver() {
 			semanage fcontext -a -t httpd_sys_content_t "$IMAGEREPO(/.*)?"
 			restorecon -Rv $IMAGEREPO
 
-			# We disable port 80 since we know it cannot be serverd via httpd
+			# We disable port 80 since we know it cannot be served via httpd
 			sed -i "/^Listen 80/c\# Listen 80" /etc/httpd/conf/httpd.conf  2>/dev/null
 	
 			systemctl restart httpd
@@ -1078,6 +1090,8 @@ process-stage-httpserver() {
 	}
 
 	[ $1 == "rollback" ] && {
+		echo "Deleting web server for install on KVM network port 8080"
+		rm /etc/httpd/conf.d/ocp-build.conf >/dev/null 2>&1
 		rollback-stage-progression "Webserver will remain running when active"
 	}
 }
@@ -1470,7 +1484,7 @@ process-stage-waitforocpinstalltocomplete() {
 
 	[ $1 == "progress" ] && {
 
-                advance-stage-progression "OCP - Complete Installation (started at: $(date +%H:%M))"  && return
+                advance-stage-progression "OCP - Complete Installation"  && return
 
 		query-user "Wait for OCP install to complete" "Y" && {
 
@@ -1499,11 +1513,25 @@ process-stage-waitforocpinstalltocomplete() {
 				echo 
 				echo The OCP Installer exited with code [ $OCPINSTALLCODE ]
 				echo Cluster has $(${OCPINSTALLSOURCE}/oc get nodes | egrep "worker|master" | wc -l) nodes and $(${OCPINSTALLSOURCE}/oc get co | awk '{ print $3 }' | grep True | wc -l) operators up 
+			else
+				echo
+				echo "IMPORTANT:"
+				echo "	- you DO NOT have a registry --> yakko ops localregistry"
+				echo "	- you cannot access the cluster from another computer --> yakko ops openaccess"
+				echo "	- you do not have any users created --> yakko ops htpasswd administrator &  yakko ops useradd <user>"
+				echo
 			fi
 
 			# We write the first time we believe the cluster was up, for reference
 			# It also let's us know that there is no further building possible
 			echo CLUSTERCOMPLETE=\"exit code [${OCPINSTALLCODE}] at [$(date)]\" >> ${CLUSTERCONFIGFILE}
+	
+			# This is my tab keeper, starting on 24/11/2020
+			# to keep track of how many clusters I've built on my big box
+			if [ "$(hostname)" == "terminus" ]
+			then
+				echo "Cluster [${CLUSTERNAME}] built on [$(date)] - Masters: ${MASTERNODECOUNT} Workers: ${WORKERNODECOUNT}" >> /YAKKO-TALLY-$(hostname)
+			fi
 			
 			echo
 			check-cluster-state 1
@@ -1636,7 +1664,7 @@ process-stage-gather-clusterconfiguration() {
 		echo "Cluster configuration to build: "
 		echo "(1) 3 Masters + 0 Workers  (all master nodes are schedulable)"
 		echo "(2) 3 Masters + 1 Worker"
-		echo "(3) 3 Masters + 2 Worker"
+		echo "(3) 3 Masters + 2 Workers"
 
 		while [ 1 ]
 		do
@@ -1843,13 +1871,16 @@ yakko-backup() {
 
 cluster-operations() {
 
+	# $1 is an op listed in $YAKKOOPERATIONALOPTIONS
+	# $2 (optional)  is used when $1 is "ops"
+
 	if [ $# -eq 0 ] # parameters go here when there is a cluster - see above and (backup: for developers)
 	then
 		check-cluster-state 1  # yakko is called on an existing cluster - check it!
 		exit
 	else
 		# YAKKOOPERATIONALOPTIONS is defined at the top with the list of valid ops on an existing cluster	
-		echo ${YAKKOOPERATIONALOPTIONS} | grep " $1 " > /dev/null
+		echo "${YAKKOOPERATIONALOPTIONS}" | grep " $1 " > /dev/null
 		if [ $? -ne 0 ]
 		then
 			# Catchall for any other passed parameted at this point
@@ -1858,10 +1889,17 @@ cluster-operations() {
 
 		if [ $1 == "startup" ]
 		then
+
+			# Sometimes, HA Proxy may not be running...
+			echo "(Re)starting HA Proxy..."
+			systemctl restart haproxy
+                        check-for-error-and-exit $? "Could not start HA Proxy, the cluster cannot function without this."
+			
 			if [ ! -z "$2" ]
 			then
 				# Surely the user knows what he's doing...
 				NODENAME=$2
+       		 		echo "Starting up: ${NODENAME}"
        		 		virsh start ${NODENAME}.${CLUSTERNAME}.${OCPDOMAIN}
 			else
 				get-node-list
@@ -1920,9 +1958,9 @@ cluster-operations() {
 			fi
 		fi
 
-		if [ $1 == "enable" ]
+		if [ $1 == "ops" ]
 		then
-			call-ocp-addons $*
+			call-ocp-operations $*
 		fi
 
 		
@@ -1998,7 +2036,8 @@ echo
 
 if [ $(whoami) != 'root' ]
 then 
-	echo MUST BE ROOT TO RUN SETUP-OCP
+	echo "ATTENTION: You must be user <root> to run ${YAKKONAME}"
+	echo
 	exit
 fi
 
