Support for OpenShift 4.10

diff --git a/yakko b/yakko
--- a/yakko
+++ b/yakko
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-YAKKOVERSION=4.0
-YAKKODATE=20220304.0951
+YAKKOVERSION=4.01
+YAKKODATE=20220315.1824
 
 ###########################################################################
 # YAKKO - Yet another KVM Konfigurator for OpenShift
@@ -125,6 +125,7 @@ populate-clusterconfigfile() {
 		echo "SYSTEMSTUBFILE_HAPROXY=${SYSTEMSTUBFILE_HAPROXY}"
 		echo "SYSTEMSTUBFILE_HTTPD=${SYSTEMSTUBFILE_HTTPD}"
 		echo "STUBFILES=${STUBFILES}"
+		echo "SELINUXSTATE=${SELINUXSTATE}"
 		
 	} > ${CLUSTERCONFIGFILE}
 
@@ -324,6 +325,19 @@ install-package-if-missing() {
 		dnf -y install $PACKAGE
 		check-for-error-and-exit $? "Failed to install package [$PACKAGE]"
 	}
+}
+
+
+set-selinux-state() {
+
+	selinuxenabled > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		SELINUXSTATE=0
+	else
+		print-in-colour orange "SELinux is disabled in this system"
+		SELINUXSTATE=1
+	fi
 }
 
 
@@ -551,39 +565,6 @@ compose-html-cluster-report() {
 	# the web server left a file index.html sitting there
 
 	# To be honest, this just makes the whole thing look more professional ;)
-
-	#lsof -i -P -n | grep LISTEN | grep "${YAKKOHOSTIP}:${WEBSERVERPORT} " > /dev/null 2>&1
-	#if [ $? -eq 1 ]
-	#then
-	#	# Nothing is listening on port ${WEBSERVERPORT} on the host side so we spruce it up 
-#
-#		{
-#
-#			echo "# WEBSERVER PAGE on host port"
-#			echo "Listen ${YAKKOHOSTIP}:${WEBSERVERPORT}"
-#			echo "<VirtualHost ${YAKKOHOSTIP}:${WEBSERVERPORT}>"
-#			echo "	DocumentRoot ${IMAGEREPO}"
-#	    		echo "	<Directory ${IMAGEREPO}>"
-#	       		echo "		Options Indexes FollowSymLinks"
-#	       		echo "		Require all granted"
-#	       		echo "		AllowOverride None"
-#	    		echo "	</Directory>"
-#			echo "</VirtualHost>"
-#	
-#		} >> ${SYSTEMSTUBFILE_HTTPD}
-#		cp ${SYSTEMSTUBFILE_HTTPD} ${STUBFILES}/httpd.conf
-#
-#		systemctl restart httpd > /dev/null 2>&1
-#		if [ $? -ne 0 ]
-#		then
-#			# OK, that didn't work for some reason, so we revert, no biggie
-#			sed -i "/WEBSERVER PAGE/,$ d" ${SYSTEMSTUBFILE_HTTPD}
-#			systemctl restart httpd > /dev/null 2>&1
-#			HTMLREPORTHOST=${CLUSTERPROXY}
-#		else
-#			HTMLREPORTHOST=${YAKKOHOSTIP}
-#		fi
-#	fi
 
 	cat <<HTMLCONTENT > ${IMAGEREPO}/index.html
 
@@ -885,7 +866,7 @@ build-ocp-node() {
 	echo "- Memory: ${NODERAMSIZE} MiB"
        	echo "- MAC Addr: ${NODEMACADDRESS}"
 
-	if [ $(echo ${OCPINSTALLVERSION} | cut -c3 ) -gt 5 ]  # We are on OCP 4.6 or higher
+	if [ ${OCPINSTALLMINORVERSION} -ge 6 ]  # We are on OCP 4.6 or higher
 	then
 		virt-install \
 			--memory=${NODERAMSIZE},maxmemory=${SYSTEMPHYSICALRAM} \
@@ -3067,6 +3048,9 @@ yakko-ops-operations() {
 	then
 		#opsnfsmap
 
+		#Lots of good stuff here:
+		#https://docs.openshift.com/container-platform/4.9/storage/persistent_storage/persistent-storage-nfs.html
+
 		print-option-header ops "Map an existing NFS share to a namespace"
 
 		echo "Here you can use an existing NFS share to be mounted and mapped to a namespace"
@@ -3792,7 +3776,7 @@ process-stage-dns() {
 				# First test
 				NAMESERVICESHOST=$(host testing.apps.${CLUSTERFQDN} | grep "has address" | awk '{ print $4 }')
 					
-				if [ ${NAMESERVICESHOST} != ${YAKKOHOSTIP} ]
+				if [ -n "${NAMESERVICESHOST}" -a "${NAMESERVICESHOST}" != ${YAKKOHOSTIP} ]
 				then
 					print-in-colour red "ALERT: Your network DNS service does not agree with the name you have given this host."
 					print-in-colour red "       This host has IP address: ${YAKKOHOSTIP}"
@@ -4114,7 +4098,7 @@ process-stage-downloadocpbinaries() {
 		
 			echo "Getting RHCOS installer files... -> $PWD"
 
-			if [ $(echo ${OCPGETCLIENTVERSION} | cut -c3) -ge 6 ]
+			if [ ${OCPINSTALLMINORVERSION} -ge 6 ]
 			then
 		
 				##### KERNEL
@@ -4160,6 +4144,7 @@ process-stage-downloadocpbinaries() {
 		# We remove the CLIENT word to make it less confusing if someone reads the ${CLUSTERCONFIGFILE} file
 		OCPINSTALLVERSION=$OCPGETCLIENTVERSION
 		echo OCPINSTALLVERSION=${OCPGETCLIENTVERSION} >> ${CLUSTERCONFIGFILE}
+		echo OCPINSTALLMINORVERSION=${OCPINSTALLMINORVERSION} >> ${CLUSTERCONFIGFILE}
 	}
 
 	[ $1 == "rollback" ] && {
@@ -4194,13 +4179,22 @@ process-stage-httpserver() {
 				install-package-if-missing lsof
 				lsof -i -P -n | grep LISTEN | grep ":${CANDIDATEPORT} " >/dev/null
 				RESULT1=$?
-				semanage port -l | grep ${CANDIDATEPORT} | grep http >/dev/null 2>&1
-				RESULT2=$?
+
+				if [ ${SELINUXSTATE} -eq 0 ] 
+				then
+					semanage port -l | grep ${CANDIDATEPORT} | grep http >/dev/null 2>&1
+					RESULT2=$?
+				else
+					RESULT2=0
+				fi
 
 				if [ $RESULT1 -eq 1 -a $RESULT2 -eq 0 ]
 				then
 					WEBSERVERPORT=$CANDIDATEPORT 
-					semanage port -a -t http_port_t -p tcp ${WEBSERVERPORT} 2>/dev/null
+					if [ ${SELINUXSTATE} -eq 0 ] 
+					then
+						semanage port -a -t http_port_t -p tcp ${WEBSERVERPORT} 2>/dev/null
+					fi
 					WEBSERVERURL=http://${WEBSERVERIP}:${WEBSERVERPORT}
 					echo "WEBSERVERPORT=${WEBSERVERPORT}" >> ${YAKKODEFAULTS}
 					echo "WEBSERVERURL=http://${WEBSERVERIP}:${WEBSERVERPORT}" >> ${YAKKODEFAULTS}
@@ -4252,18 +4246,22 @@ process-stage-httpserver() {
 			} > ${SYSTEMSTUBFILE_HTTPD}
 			cp ${SYSTEMSTUBFILE_HTTPD} ${STUBFILES}/httpd.conf
 		
-			# Figure out which of these are required
-			# and needed to survive a reboot...
-			chcon  --user system_u --type httpd_sys_content_t -Rv $IMAGEREPO
-			check-for-error-and-exit $? "Failed to change security context (chcon) for $IMAGEREPO (filesystem type is $(stat -f -c %T $IMAGEREPO))"
-			semanage fcontext -a -t httpd_sys_content_t "$IMAGEREPO(/.*)?"
-			if [ $? -ne 0 ]
+			if [ ${SELINUXSTATE} -eq 0 ]
 			then
-				semanage fcontext -m -t httpd_sys_content_t "$IMAGEREPO(/.*)?"
-				check-for-error-and-exit $? "Failed to change security context (semanage fcontext) for files in $IMAGEREPO"
+				# Figure out which of these SELinux values are required
+				# and needed to survive a reboot...
+
+				chcon  --user system_u --type httpd_sys_content_t -Rv $IMAGEREPO
+				check-for-error-and-exit $? "Failed to change security context (chcon) for $IMAGEREPO (filesystem type is $(stat -f -c %T $IMAGEREPO))"
+				semanage fcontext -a -t httpd_sys_content_t "$IMAGEREPO(/.*)?"
+				if [ $? -ne 0 ]
+				then
+					semanage fcontext -m -t httpd_sys_content_t "$IMAGEREPO(/.*)?"
+					check-for-error-and-exit $? "Failed to change security context (semanage fcontext) for files in $IMAGEREPO"
+				fi
+				restorecon -Rv $IMAGEREPO
+				check-for-error-and-exit $? "Failed to restore context (restorecon) for files in $IMAGEREPO"
 			fi
-			restorecon -Rv $IMAGEREPO
-			check-for-error-and-exit $? "Failed to restore context (restorecon) for files in $IMAGEREPO"
 
 			# We disable port 80 since we know it should not be served via httpd
 			# Note that this is done directly on the system, not on the yakko httpd conf file in stubfiles
@@ -4414,7 +4412,10 @@ process-stage-generateocpinstallerconfig() {
 				echo "- hyperthreading: ${HYPERTHREADING}"
 				echo "  name: worker"
 				echo "  replicas: 0"
-				echo "  skipMachinePools: true"
+				if [ ${OCPINSTALLMINORVERSION} -lt 10 ] # This is an OCP 4.10 thing, not sure use case
+				then
+					echo "  skipMachinePools: true"
+				fi
 				echo "controlPlane:"
 				echo "  hyperthreading: ${HYPERTHREADING}"
 				echo "  name: master"
@@ -4819,6 +4820,8 @@ process-stage-waitforocpinstalltocomplete() {
 			echo "- oc get nodes ------------>  To see nodes and node status"
 			echo 
 			echo "---------------------------------------------------------------------------"
+			echo "Ouput below tracks  command 'openshift-install --dir=$CLUSTERSETUPDIR wait-for install-complete'"
+			echo "---------------------------------------------------------------------------"
 			echo
 		
 			$OCPINSTALLSOURCE/openshift-install --dir=$CLUSTERSETUPDIR wait-for install-complete 
@@ -4857,7 +4860,7 @@ process-stage-waitforocpinstalltocomplete() {
 
 				echo
 				print-in-colour ${YAKKOTEXTCOLOR} "IMPORTANT:"
-				print-in-colour ${YAKKOTEXTCOLOR} " - you can bookmark cluster info at http://${HTMLREPORTHOST}:${WEBSERVERPORT}"
+				print-in-colour ${YAKKOTEXTCOLOR} " - you can bookmark cluster info at http://${YAKKOHOSTIP}:${WEBSERVERPORT}"
 				print-in-colour ${YAKKOTEXTCOLOR} " - you DO NOT have a registry -> yakko ops localregistry"
 				print-in-colour ${YAKKOTEXTCOLOR} " - you cannot access the cluster from another computer -> yakko infra openaccess"
 				print-in-colour ${YAKKOTEXTCOLOR} " - you have no user DB-> yakko ops htpasswd administrator &  yakko ops useradd <user>"
@@ -4869,10 +4872,10 @@ process-stage-waitforocpinstalltocomplete() {
 					print-in-colour red "ALERT: Your network DNS service does not agree with the name you have given this host."
 					print-in-colour red "       This host has IP address: ${YAKKOHOSTIP}"
 					print-in-colour red "       The external name lookup for the cluster FQDN returns IP address: ${NAMESERVICESHOST}"
-					echo
+					print-in-colour ${YAKKOTEXTCOLOR} ${SEPARATIONLINE}
 				fi
-
-				print-in-colour ${YAKKOTEXTCOLOR} ${SEPARATIONLINE}
+				echo
+				echo
 
 				# We build the 'last successful config' file for further auto
 				if [ ! -e ${LASTBUILDCONFIG} -o -w ${LASTBUILDCONFIG} ]
@@ -4903,7 +4906,7 @@ process-stage-waitforocpinstalltocomplete() {
 						fi
 					done
 				fi
-				echo
+
 				check-cluster-state 1
 			fi
 		}
@@ -5118,7 +5121,7 @@ process-stage-gatherclusterconfiguration() {
 
 			# regular releases are at:
 			# INSTALLER: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest
-			# IMAGES: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
+			# IMAGES: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest (with OCP 4.10 it seems to be just 'latest')
 
 			# pre-release are at:
 			# INSTALLER: https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest
@@ -5134,7 +5137,16 @@ process-stage-gatherclusterconfiguration() {
 		
 			# This would get you the number for the latest version
 			OCPDOWNLOADCLIENT="$OCPROOT/clients/ocp/latest"
-			OCPDOWNLOADIMAGE="$OCPROOT/dependencies/rhcos/latest/latest"
+
+			OCPDOWNLOADIMAGE="$OCPROOT/dependencies/rhcos/latest/latest" # OCP 4.10 change to layout?
+			wget ${OCPDOWNLOADIMAGE} >/dev/null 2>&1
+			if [ $? -ne 0 ]
+			then
+				# latest/latest seemed to be the mirror dir up until OCP 4.9
+
+				# If the below fails, the release.txt get below will fail anyway
+				OCPDOWNLOADIMAGE="$OCPROOT/dependencies/rhcos/latest" # OCP 4.10 change to layout?
+			fi
 
 			echo -n "Checking for latest OpenShift version - please wait  "
 			wget -O $OCPWGETTMP $OCPDOWNLOADCLIENT/release.txt > /dev/null 2>&1
@@ -5142,7 +5154,7 @@ process-stage-gatherclusterconfiguration() {
 			blank-line
 				
 		        OCPGETCLIENTVERSION=$(cat $OCPWGETTMP | grep Version: | awk '{ print $2 }')
-
+			OCPINSTALLMINORVERSION=$(echo $OCPGETCLIENTVERSION | cut -f2 -d.)
 			OCPIMAGESONFILE=$(ls -d images/[0-9]* 2>/dev/null | cut -f2 -d/)
 
 			while true
@@ -5278,26 +5290,30 @@ process-stage-gatherclusterconfiguration() {
 					continue
 				else
 
-					# The following was discovered by Wayne Boxall, adequate check
-					# https://docs.fedoraproject.org/en-US/Fedora/13/html/Virtualization_Guide/sect-Virtualization-Security_for_virtualization-SELinux_and_virtualization.html
-					semanage fcontext -a -t virt_image_t "${OCPVMDISKDIR}(/.*)?" >/dev/null 2>&1
-					ERROR=$?
-					if [ $ERROR -ne 0 -a $ERROR -ne 1 ]
+					if [ ${SELINUXSTATE} -eq 0 ]
 					then
-						echo "ERROR: Could not set virt_image_t context on directory [${OCPVMDISKDIR}] (fcontext error #$ERROR)"
-						echo "       specify another directory or CTRL-C to inspect your system."
-						echo
-						continue
-					fi
+						# The following was discovered by Wayne Boxall, adequate check
+						# https://docs.fedoraproject.org/en-US/Fedora/13/html/Virtualization_Guide/sect-Virtualization-Security_for_virtualization-SELinux_and_virtualization.html
 
-					restorecon -R -v "${OCPVMDISKDIR}" >/dev/null 2>&1
-					ERROR=$?
-					if [ $ERROR -ne 0 ]
-					then
-						echo "ERROR: Could not set virt_image_t restorecon context on directory [${OCPVMDISKDIR}] (restorecon error #$ERROR)"
-						echo "       specify another directory or CTRL-C to inspect your system."
-						echo
-						continue
+						semanage fcontext -a -t virt_image_t "${OCPVMDISKDIR}(/.*)?" >/dev/null 2>&1
+						ERROR=$?
+						if [ $ERROR -ne 0 -a $ERROR -ne 1 ]
+						then
+							echo "ERROR: Could not set virt_image_t context on directory [${OCPVMDISKDIR}] (fcontext error #$ERROR)"
+							echo "       specify another directory or CTRL-C to inspect your system."
+							echo
+							continue
+						fi
+
+						restorecon -R -v "${OCPVMDISKDIR}" >/dev/null 2>&1
+						ERROR=$?
+						if [ $ERROR -ne 0 ]
+						then
+							echo "ERROR: Could not set virt_image_t restorecon context on directory [${OCPVMDISKDIR}] (restorecon error #$ERROR)"
+							echo "       specify another directory or CTRL-C to inspect your system."
+							echo
+							continue
+						fi
 					fi
 				fi
 
@@ -5341,7 +5357,7 @@ process-stage-gatherclusterconfiguration() {
 
 			while true 
 			do
-				if [ $(echo $OCPGETCLIENTVERSION | cut -f2 -d.) -ge 8  ]
+				if [ ${OCPINSTALLMINORVERSION} -ge 8  ]
 				then
 					### QUESTION: Master node count 
 					print-question-separator MASTER NODE COUNT
@@ -5548,6 +5564,9 @@ process-stage-gatherclusterconfiguration() {
 		# This in case there is more than one cluster defined... Maybe...
 		BASEMACADDRESS=${COREMACADDRESS}:$(echo ${BASENETWORK} | cut -f3 -d. | xargs printf '%x')
 
+		# Is SELinux running?
+		set-selinux-state
+
 		populate-clusterconfigfile
 		populate-yakkodefaults
 
@@ -5639,6 +5658,8 @@ yakko-process-stages() {
 
 YAKKODIRECTORY=$(dirname $(realpath $0))
 YAKKOEXECUTABLE=$(realpath $0)
+
+set-selinux-state  # Identify this from the get go
 
 if [ "$1" == "version" ]
 then
@@ -5833,7 +5854,6 @@ then
 	yakko-infra-operations purgedownloads
 fi
 	
-
 if [ ! -r ${CLUSTERCONFIGFILE} ]
 then
 
